# My request chaining for REST Client (VS Code extension)
# =======================================================

@host = http://127.0.0.1:8000/api/
@user_password = secret13
# @user_name = achekhov
@user_name = ikruglov

### Create user through API (Djoser + rest_framework.authtoken (NOT JWT))
# @name create_user
POST {{ host }}users/
Content-Type: application/json

{
  "username": "{{ user_name }}",
  "password": "{{ user_password }}"
}

### Obtain users token (Djoser + rest_framework.authtoken)
# @name request_user_token
POST {{ host }}token/login/
Content-Type: application/json

{
    "username": "{{ user_name }}",
    "password": "{{ user_password }}"
}

### Extract the access token from the response and use it in the next request
@user_token = {{ request_user_token.response.body.auth_token }}

### Get the list of cats using the extracted users token
GET {{ host }}cats/
Authorization: Token {{ user_token }}

### Get the list of users using the extracted users token
GET {{ host }}users/
Authorization: Token {{ user_token }}

### Get the list of achievements using the extracted users token
GET {{ host }}achievements/
Authorization: Token {{ user_token }}


### Get one User object
GET {{ host }}users/1/
Authorization: Token {{ user_token }}

### Get one Cat object
GET {{ host }}cats/1/
# Authorization: Token {{ user_token }}


### Create one Cat object (with Hex2NameColor)
POST {{ host }}cats/
Content-Type: application/json
Authorization: Token {{ user_token }}

# {
#     "name": "Bulochka",
#     "color": "#FFD700",
#     "birth_year": 2005,
#     "owner": 2,
#     "achievements": [
#         {"achievement_name": "поймал мышку"},
#         {"achievement_name": "разбил вазу"}
#     ],
#     "image": "data:image/png;base64,iVBORw0KGgoAAAANSU...5CYII="
# }

{
    "name": "Lev",
    "color": "#000000",
    "birth_year": 2021
}

# IsAuthenticatedOrReadOnly
### Get the list of cats using the extracted users token
GET {{ host }}cats/


# Test custom permission (from user ikruglov try to change
#  achekhov cat
###
PATCH  {{ host }}cats/1/
Content-Type: application/json
Authorization: Token {{ user_token }}

{
    "birth_year": 1666
}

# Test custom permission (from user ikruglov try to delete
#  achekhov cat
###
DELETE {{ host }}cats/1/
Authorization: Token {{ user_token }}


# LimitOffsetPagination
### Get the list of cats with number of return obj = limit and start from obj = offset
# offset = 0 is the first obj
GET {{ host }}cats/?limit=2&offset=0


# Фильтрация: бэкенд DjangoFilterBackend
### Get the list of all Black cats
GET {{ host }}cats/?color=Black

# Поиск: бэкенд SearchFilter
### Get the list of all cats which names contain 'bul' (case-insensitive)
GET {{ host }}cats/?search=bul

# Поиск: бэкенд SearchFilter
### Можно искать по нескольким совпадениям: в запросе их надо разделить запятыми, без пробелов.
# В выдачу попадут только те котики, где есть одновременно все совпадения, например — «Кеша».
GET {{ host }}cats/?search=К,ша

# Сортировка выдачи: бэкенд OrderingFilter
### Get the list of all cats ordered by name (reversed is -name)
GET {{ host }}cats/?ordering=name

### Get the list of all cats ordered by name and birth_year
GET {{ host }}cats/?ordering=name,birth_year